#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Debenhams.Resource", IsApplication=true)]

namespace Debenhams
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int debenhams = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int EditableTextStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int EditTextStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int passwordloginbutton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int searchbutton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int TextBorder = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int TextBorderBotton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int TextSmall = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int userloginbutton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int warning = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060027
			public const int ActLeftDrawer = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int FlyOutContent = 2131099688;
			
			// aapt resource value: 0x7f060003
			public const int FlyOutMenu = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Layout1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int MenuPicking = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int MenuPicking1 = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int MenuReceiving = 2131099654;
			
			// aapt resource value: 0x7f060030
			public const int TableLayout1 = 2131099696;
			
			// aapt resource value: 0x7f060033
			public const int TableLayout2 = 2131099699;
			
			// aapt resource value: 0x7f060057
			public const int TableLayout3 = 2131099735;
			
			// aapt resource value: 0x7f06004c
			public const int TableLayout4 = 2131099724;
			
			// aapt resource value: 0x7f060032
			public const int btnDone = 2131099698;
			
			// aapt resource value: 0x7f060058
			public const int btnScanSKU = 2131099736;
			
			// aapt resource value: 0x7f060053
			public const int btnScanSlot = 2131099731;
			
			// aapt resource value: 0x7f060031
			public const int btnScanUpc = 2131099697;
			
			// aapt resource value: 0x7f06005c
			public const int btnUnload = 2131099740;
			
			// aapt resource value: 0x7f060018
			public const int btnaddbox = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int btncreatebox = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int btndonebox = 2131099673;
			
			// aapt resource value: 0x7f060012
			public const int btnlogin = 2131099666;
			
			// aapt resource value: 0x7f06004e
			public const int btnqtyminus = 2131099726;
			
			// aapt resource value: 0x7f06002b
			public const int btnsearch = 2131099691;
			
			// aapt resource value: 0x7f060015
			public const int frameLayout1 = 2131099669;
			
			// aapt resource value: 0x7f06005d
			public const int imageView1 = 2131099741;
			
			// aapt resource value: 0x7f06000f
			public const int imgLogo = 2131099663;
			
			// aapt resource value: 0x7f060040
			public const int lblDept = 2131099712;
			
			// aapt resource value: 0x7f060049
			public const int lblDescription = 2131099721;
			
			// aapt resource value: 0x7f06002e
			public const int lblLot = 2131099694;
			
			// aapt resource value: 0x7f060043
			public const int lblOQty = 2131099715;
			
			// aapt resource value: 0x7f06002d
			public const int lblPO = 2131099693;
			
			// aapt resource value: 0x7f060046
			public const int lblPalletNo = 2131099718;
			
			// aapt resource value: 0x7f060054
			public const int lblPo = 2131099732;
			
			// aapt resource value: 0x7f06003d
			public const int lblQty = 2131099709;
			
			// aapt resource value: 0x7f060044
			public const int lblRQty = 2131099716;
			
			// aapt resource value: 0x7f06003e
			public const int lblSKU = 2131099710;
			
			// aapt resource value: 0x7f06004f
			public const int lblStatus = 2131099727;
			
			// aapt resource value: 0x7f060041
			public const int lblStyle = 2131099713;
			
			// aapt resource value: 0x7f060034
			public const int lblTlno = 2131099700;
			
			// aapt resource value: 0x7f060042
			public const int lblUPC = 2131099714;
			
			// aapt resource value: 0x7f060026
			public const int lblboxnum = 2131099686;
			
			// aapt resource value: 0x7f060037
			public const int lbldivision = 2131099703;
			
			// aapt resource value: 0x7f06003b
			public const int lblslot = 2131099707;
			
			// aapt resource value: 0x7f060024
			public const int lbltl_no = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout2 = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout3 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int linearLayout4 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int linearLayout5 = 2131099685;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout6 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout7 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout8 = 2131099677;
			
			// aapt resource value: 0x7f06000d
			public const int logo = 2131099661;
			
			// aapt resource value: 0x7f06003f
			public const int lvUpc = 2131099711;
			
			// aapt resource value: 0x7f06002f
			public const int lvpo = 2131099695;
			
			// aapt resource value: 0x7f060029
			public const int menuHdrButton = 2131099689;
			
			// aapt resource value: 0x7f06005e
			public const int myButton = 2131099742;
			
			// aapt resource value: 0x7f060021
			public const int spnbox = 2131099681;
			
			// aapt resource value: 0x7f06002c
			public const int tableRow1 = 2131099692;
			
			// aapt resource value: 0x7f060036
			public const int tableRow2 = 2131099702;
			
			// aapt resource value: 0x7f06003a
			public const int tableRow3 = 2131099706;
			
			// aapt resource value: 0x7f06004d
			public const int tableRow4 = 2131099725;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int textView3 = 2131099678;
			
			// aapt resource value: 0x7f06003c
			public const int txtBoxCode = 2131099708;
			
			// aapt resource value: 0x7f060048
			public const int txtBoxNo = 2131099720;
			
			// aapt resource value: 0x7f060047
			public const int txtDescr = 2131099719;
			
			// aapt resource value: 0x7f06000a
			public const int txtLoading = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int txtLogout = 2131099660;
			
			// aapt resource value: 0x7f06004a
			public const int txtOQty = 2131099722;
			
			// aapt resource value: 0x7f060013
			public const int txtPassword = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int txtPickingEaches = 2131099657;
			
			// aapt resource value: 0x7f06004b
			public const int txtRQTY = 2131099723;
			
			// aapt resource value: 0x7f06000b
			public const int txtReverseLogistics = 2131099659;
			
			// aapt resource value: 0x7f060039
			public const int txtScanUPC = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int txtStoreName = 2131099704;
			
			// aapt resource value: 0x7f060035
			public const int txtTlno = 2131099701;
			
			// aapt resource value: 0x7f060045
			public const int txtUPC = 2131099717;
			
			// aapt resource value: 0x7f060011
			public const int txtUserName = 2131099665;
			
			// aapt resource value: 0x7f06005b
			public const int txtdescription = 2131099739;
			
			// aapt resource value: 0x7f060051
			public const int txtdivision = 2131099729;
			
			// aapt resource value: 0x7f060010
			public const int txtpassword = 2131099664;
			
			// aapt resource value: 0x7f060050
			public const int txtpo_num = 2131099728;
			
			// aapt resource value: 0x7f060055
			public const int txtponum = 2131099733;
			
			// aapt resource value: 0x7f06005a
			public const int txtqty = 2131099738;
			
			// aapt resource value: 0x7f06002a
			public const int txtsearch = 2131099690;
			
			// aapt resource value: 0x7f060056
			public const int txtslot = 2131099734;
			
			// aapt resource value: 0x7f060052
			public const int txtstatus = 2131099730;
			
			// aapt resource value: 0x7f06001f
			public const int txtstore_name = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int txttl_no = 2131099676;
			
			// aapt resource value: 0x7f060059
			public const int txtupc = 2131099737;
			
			// aapt resource value: 0x7f060002
			public const int txturl = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int txtusername = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int view1 = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int view2 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int LayInputURL = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int LayLeftDrawer = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LayLogin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LayPBox = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int LayPTLList = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int LayPTLListC = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int LayPTLLists = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int LayPTLScanList = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int LayPTLScanLists = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int LayPTLUpc = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LayRPoList = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int LayRPoListC = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int LayRPoLists = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int LayRPoScanList = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int LayRPoScanLists = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int LayRPoUpc = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int LayStart = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Main = 2130968593;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int notavailable = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int search = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
